/**
 * Script to populate ChromaDB with educational content
 * 
 * Run with: npx tsx scripts/populateChromaDB.ts
 */

import { addDocuments, initChromaDB, getCollectionStats } from '../lib/chromaService';

// Educational content for CMA/CPA courses
const educationalContent = [
  // Financial Statement Analysis
  {
    id: 'fsa-001',
    content: 'Financial Statement Analysis is the process of reviewing and analyzing a company\'s financial statements to make better economic decisions. This involves examining the balance sheet, income statement, and cash flow statement to assess the company\'s financial health, performance, and cash flow generation.',
    metadata: {
      topic: 'Financial Statement Analysis',
      category: 'Financial Accounting',
      keywords: ['Financial Statement Analysis', 'financial health', 'performance analysis'],
      page: 45,
      source: 'CMA Study Guide - Part 1',
    },
  },
  {
    id: 'fsa-002',
    content: 'Ratio Analysis is a quantitative method of gaining insight into a company\'s liquidity, operational efficiency, and profitability by comparing information contained in its financial statements. Common ratios include the current ratio, quick ratio, return on assets (ROA), return on equity (ROE), and debt-to-equity ratio.',
    metadata: {
      topic: 'Ratio Analysis',
      category: 'Financial Analysis',
      keywords: ['Ratio Analysis', 'liquidity', 'profitability', 'efficiency ratios'],
      page: 52,
      source: 'CPA Financial Accounting',
    },
  },
  {
    id: 'fsa-003',
    content: 'Horizontal Analysis (also called trend analysis) is a financial statement analysis technique that shows changes in the amounts of corresponding financial statement items over a period of time. It is useful in evaluating trends by comparing financial data over multiple periods.',
    metadata: {
      topic: 'Horizontal Analysis',
      category: 'Financial Analysis',
      keywords: ['Horizontal Analysis', 'trend analysis', 'financial trends'],
      page: 58,
      source: 'CMA Study Guide - Part 1',
    },
  },
  {
    id: 'fsa-004',
    content: 'Vertical Analysis (also known as common-size analysis) expresses each item in a financial statement as a percentage of a base figure. For the income statement, each line item is expressed as a percentage of gross sales. For the balance sheet, each line item is expressed as a percentage of total assets.',
    metadata: {
      topic: 'Vertical Analysis',
      category: 'Financial Analysis',
      keywords: ['Vertical Analysis', 'common-size analysis', 'percentage analysis'],
      page: 61,
      source: 'CPA Financial Accounting',
    },
  },

  // Cost Accounting
  {
    id: 'ca-001',
    content: 'Cost of Goods Sold (COGS) represents the direct costs attributable to the production of the goods sold by a company. The formula is: Beginning Inventory + Purchases - Ending Inventory = Cost of Goods Sold. COGS is reported on the income statement and is subtracted from revenue to calculate gross profit.',
    metadata: {
      topic: 'Cost of Goods Sold',
      category: 'Cost Accounting',
      keywords: ['Cost of Goods Sold', 'COGS', 'inventory', 'gross profit'],
      page: 125,
      source: 'CMA Cost Management',
    },
  },
  {
    id: 'ca-002',
    content: 'Variable Costs are expenses that change in proportion to the production volume or activity level. Unlike fixed costs which remain constant regardless of output, variable costs increase as production increases and decrease as production decreases. Common examples include direct materials, direct labor, and sales commissions.',
    metadata: {
      topic: 'Variable Cost',
      category: 'Cost Accounting',
      keywords: ['Variable Cost', 'variable expenses', 'cost behavior'],
      page: 132,
      source: 'CMA Cost Management',
    },
  },
  {
    id: 'ca-003',
    content: 'Manufacturing Overhead consists of all indirect costs associated with production that cannot be directly traced to specific products. This includes indirect materials, indirect labor, utilities, depreciation on factory equipment, factory rent, and property taxes. Overhead is typically applied to products using a predetermined overhead rate.',
    metadata: {
      topic: 'Manufacturing Overhead',
      category: 'Cost Accounting',
      keywords: ['Overhead', 'Manufacturing Overhead', 'indirect costs', 'overhead rate'],
      page: 145,
      source: 'CMA Cost Management',
    },
  },

  // Capital Budgeting
  {
    id: 'cb-001',
    content: 'Net Present Value (NPV) is a capital budgeting method used to evaluate the profitability of an investment or project. NPV calculates the present value of all future cash flows (both inflows and outflows) generated by a project, discounted at the company\'s required rate of return. The formula is: NPV = Σ[CF_t / (1+r)^t] - Initial Investment. A positive NPV indicates the project will add value to the firm.',
    metadata: {
      topic: 'Net Present Value',
      category: 'Capital Budgeting',
      keywords: ['Net Present Value', 'NPV', 'capital budgeting', 'present value', 'discount rate'],
      page: 215,
      source: 'CMA Financial Decision Making',
    },
  },
  {
    id: 'cb-002',
    content: 'Internal Rate of Return (IRR) is the discount rate that makes the net present value (NPV) of all cash flows from a particular project equal to zero. In other words, it\'s the rate at which the present value of cash inflows equals the present value of cash outflows. A project is typically accepted if its IRR exceeds the company\'s required rate of return (hurdle rate).',
    metadata: {
      topic: 'Internal Rate of Return',
      category: 'Capital Budgeting',
      keywords: ['Internal Rate of Return', 'IRR', 'discount rate', 'hurdle rate'],
      page: 222,
      source: 'CMA Financial Decision Making',
    },
  },

  // Cash Flow
  {
    id: 'cf-001',
    content: 'The Statement of Cash Flows is one of the three primary financial statements and provides detailed information about a company\'s cash inflows and outflows during a specific period. It is divided into three sections: Operating Activities (cash from normal business operations), Investing Activities (cash from buying/selling long-term assets), and Financing Activities (cash from debt, equity, and dividends). This statement is essential for assessing liquidity and financial flexibility.',
    metadata: {
      topic: 'Statement of Cash Flows',
      category: 'Financial Accounting',
      keywords: ['Statement of Cash Flows', 'cash flows', 'operating activities', 'investing activities', 'financing activities'],
      page: 98,
      source: 'CPA Financial Accounting',
    },
  },
  {
    id: 'cf-002',
    content: 'Free Cash Flow (FCF) represents the cash a company generates after accounting for cash outflows to support operations and maintain capital assets. The formula is: Operating Cash Flow - Capital Expenditures. FCF is important because it allows a company to pursue opportunities that enhance shareholder value. A company with strong FCF can reduce debt, pay dividends, or invest in growth.',
    metadata: {
      topic: 'Free Cash Flow',
      category: 'Financial Analysis',
      keywords: ['Free Cash Flow', 'FCF', 'operating cash flow', 'capital expenditures'],
      page: 105,
      source: 'CMA Financial Decision Making',
    },
  },

  // Liquidity Ratios
  {
    id: 'lr-001',
    content: 'The Current Ratio is a liquidity ratio that measures a company\'s ability to pay short-term obligations or those due within one year. The formula is: Current Assets / Current Liabilities. A ratio above 1.0 indicates the company has more current assets than current liabilities. Generally, a current ratio between 1.5 and 3.0 is considered healthy, though this varies by industry.',
    metadata: {
      topic: 'Current Ratio',
      category: 'Financial Ratios',
      keywords: ['Current Ratio', 'liquidity ratio', 'working capital', 'current assets', 'current liabilities'],
      page: 168,
      source: 'CPA Financial Accounting',
    },
  },
  {
    id: 'lr-002',
    content: 'The Quick Ratio (also called the Acid-Test Ratio) is a more conservative liquidity ratio that excludes inventory from current assets. The formula is: (Current Assets - Inventory) / Current Liabilities. This ratio provides a more stringent test of liquidity because inventory may not be easily converted to cash. A quick ratio of 1.0 or higher is generally considered good.',
    metadata: {
      topic: 'Quick Ratio',
      category: 'Financial Ratios',
      keywords: ['Quick Ratio', 'Acid-Test Ratio', 'liquidity', 'current assets'],
      page: 171,
      source: 'CPA Financial Accounting',
    },
  },

  // Profitability Ratios
  {
    id: 'pr-001',
    content: 'Return on Assets (ROA) is a profitability ratio that indicates how efficiently a company uses its assets to generate profit. The formula is: Net Income / Total Assets. ROA shows how much profit a company earns for every dollar of assets it owns. A higher ROA indicates more efficient use of assets. This ratio is particularly useful for comparing companies within the same industry.',
    metadata: {
      topic: 'Return on Assets',
      category: 'Profitability Ratios',
      keywords: ['Return on Assets', 'ROA', 'profitability', 'asset efficiency'],
      page: 185,
      source: 'CMA Performance Management',
    },
  },
  {
    id: 'pr-002',
    content: 'Return on Equity (ROE) measures the profitability of a company in relation to shareholders\' equity. The formula is: Net Income / Shareholders\' Equity. ROE shows how much profit a company generates with the money shareholders have invested. A higher ROE suggests more efficient use of equity capital. ROE is a key metric for equity investors as it indicates the return on their investment.',
    metadata: {
      topic: 'Return on Equity',
      category: 'Profitability Ratios',
      keywords: ['Return on Equity', 'ROE', 'profitability', 'shareholders equity'],
      page: 188,
      source: 'CMA Performance Management',
    },
  },

  // Break-Even Analysis
  {
    id: 'be-001',
    content: 'Break-Even Analysis determines the point at which total revenue equals total costs, meaning the business is neither making a profit nor a loss. The break-even point in units is calculated as: Fixed Costs / (Selling Price per Unit - Variable Cost per Unit). This is also known as dividing fixed costs by the contribution margin per unit. Understanding the break-even point helps businesses set sales targets and pricing strategies.',
    metadata: {
      topic: 'Break-Even Analysis',
      category: 'Cost Management',
      keywords: ['Break-Even Analysis', 'break-even point', 'contribution margin', 'fixed costs'],
      page: 245,
      source: 'CMA Cost Management',
    },
  },
  {
    id: 'be-002',
    content: 'Contribution Margin is the amount of revenue remaining after deducting variable costs. It represents the portion of sales revenue that contributes to covering fixed costs and generating profit. The formula is: Sales Revenue - Variable Costs = Contribution Margin. The contribution margin ratio is: Contribution Margin / Sales Revenue. This metric is crucial for break-even analysis and profit planning.',
    metadata: {
      topic: 'Contribution Margin',
      category: 'Cost Management',
      keywords: ['Contribution Margin', 'variable costs', 'break-even', 'profit planning'],
      page: 248,
      source: 'CMA Cost Management',
    },
  },
];

/**
 * Main function to populate ChromaDB
 */
async function main() {
  try {
    console.log('🚀 Starting ChromaDB population...\n');

    // Initialize ChromaDB
    await initChromaDB();

    // Prepare documents for insertion
    const documents = educationalContent.map((item) => item.content);
    const metadatas = educationalContent.map((item) => item.metadata);
    const ids = educationalContent.map((item) => item.id);

    // Add documents to ChromaDB
    console.log(`📚 Adding ${documents.length} educational documents...\n`);
    await addDocuments(documents, metadatas, ids);

    // Get collection stats
    const stats = await getCollectionStats();
    console.log('\n📊 Collection Statistics:');
    console.log(`   - Collection: ${stats.collection_name}`);
    console.log(`   - Documents: ${stats.document_count}`);
    console.log(`   - Status: ${stats.status}\n`);

    console.log('✅ ChromaDB population completed successfully!\n');
    console.log('💡 You can now use semantic search for educational content.');
    console.log('   Example topics:');
    educationalContent.slice(0, 5).forEach((item) => {
      console.log(`   - ${item.metadata.topic}`);
    });
    console.log('');

    process.exit(0);
  } catch (error) {
    console.error('\n❌ Error populating ChromaDB:', error);
    console.log('\n💡 Make sure ChromaDB is running:');
    console.log('   docker run -p 8000:8000 chromadb/chroma\n');
    process.exit(1);
  }
}

// Run the script
main();

